### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [andrewp-as-is/dotfiles#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`brew-cask.txt`](https://github.com/andrewp-as-is/dotfiles/blob/c924b493aeac0b9bbc989600624cb70aff30c56c/macOS/brew/brew-cask.txt). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by andrewpetrochenkov** [comment]
done
